#!/usr/bin/bash -xe

t:
  pnpm run test

b:
  pnpm run build

d:
  pnpm run dev

w/:
  pushd web
  d:
    pnpm run dev
  c:
    pnpm run check
  popd

c/:
  pushd packages/core
  b:
    pnpm run build
  t:
    pnpm run test
  popd

x/:
  pushd packages/block-to-xlsx
  b:
    pnpm run build
  t:
    pnpm run test
  popd
