#!/usr/bin/bash -xe

# t/:
#   table:
#     bun test src/lib/json-to-table.test.ts
#   bun test

w/:
  pushd web
  d:
    pnpm run dev
  c:
    pnpm run check
  popd

c/:
  pushd packages/core
  b:
    pnpm run build
  t:
    pnpm run test
  popd